// Generated by FrontendAgent
import React from 'react';
import { Button, Input, Card } from '@/components/ui';
import { cn } from '@/lib/utils';

interface Assignment {
  id: number;
  title: string;
  description: string;
  dueDate: string;
  course: string;
}

interface AssignmentListProps {
  assignments: Assignment[];
}

const AssignmentList: React.FC<AssignmentListProps> = ({ assignments }) => {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Assignments</h1>
      <Input
        type="text"
        placeholder="Search assignments..."
        className="mb-4"
      />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {assignments.map((assignment) => (
          <Card key={assignment.id} className="p-4 shadow-md">
            <h2 className="text-xl font-semibold mb-2">{assignment.title}</h2>
            <p className="text-gray-700 mb-2">{assignment.description}</p>
            <p className="text-gray-500 mb-2">Due: {assignment.dueDate}</p>
            <p className="text-gray-500 mb-4">Course: {assignment.course}</p>
            <Button className={cn('w-full', 'bg-blue-500 text-white')}>
              View Assignment
            </Button>
          </Card>
        ))}
      </div>
    </div>
  );
};

export default AssignmentList;