// Generated by FrontendAgent
import React from 'react';
import { Button, Card } from '@/components/ui';
import { cn } from '@/lib/utils';

interface CourseCardProps {
  title: string;
  description: string;
  instructor: string;
  duration: string;
  enrollment: number;
  onEnroll: () => void;
}

const CourseCard: React.FC<CourseCardProps> = ({
  title,
  description,
  instructor,
  duration,
  enrollment,
  onEnroll,
}) => {
  return (
    <Card className="w-full max-w-sm mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
      <div className="p-4">
        <h2 className="text-xl font-bold mb-2">{title}</h2>
        <p className="text-gray-700 mb-4">{description}</p>
        <div className="mb-4">
          <p className="text-gray-600">Instructor: {instructor}</p>
          <p className="text-gray-600">Duration: {duration}</p>
          <p className="text-gray-600">Enrollment: {enrollment}</p>
        </div>
        <Button
          onClick={onEnroll}
          className={cn(
            'w-full bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600',
            'focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75'
          )}
        >
          Enroll Now
        </Button>
      </div>
    </Card>
  );
};

export default CourseCard;