// Generated by FrontendAgent
import React, { useState } from 'react';
import { Button, Input, Card } from '@/components/ui';
import { cn } from '@/lib/utils';

interface DiscussionForumProps {
  initialComments: Comment[];
}

interface Comment {
  id: number;
  user: string;
  content: string;
  replies: Comment[];
}

const DiscussionForum: React.FC<DiscussionForumProps> = ({ initialComments }) => {
  const [comments, setComments] = useState<Comment[]>(initialComments);
  const [newComment, setNewComment] = useState<string>('');

  const handleAddComment = () => {
    if (newComment.trim()) {
      const newCommentObj: Comment = {
        id: Date.now(),
        user: 'CurrentUser', // Replace with actual user logic
        content: newComment,
        replies: [],
      };
      setComments([newCommentObj, ...comments]);
      setNewComment('');
    }
  };

  const handleAddReply = (commentId: number, replyContent: string) => {
    const updatedComments = comments.map(comment => {
      if (comment.id === commentId) {
        const newReply: Comment = {
          id: Date.now(),
          user: 'CurrentUser', // Replace with actual user logic
          content: replyContent,
          replies: [],
        };
        return { ...comment, replies: [newReply, ...comment.replies] };
      }
      return comment;
    });
    setComments(updatedComments);
  };

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Discussion Forum</h1>
      <div className="mb-4">
        <Input
          type="text"
          value={newComment}
          onChange={(e) => setNewComment(e.target.value)}
          placeholder="Add a new comment"
          className="w-full"
        />
        <Button onClick={handleAddComment} className="mt-2">
          Post Comment
        </Button>
      </div>
      <div className="space-y-4">
        {comments.map(comment => (
          <Card key={comment.id} className="p-4">
            <div className="flex justify-between items-center mb-2">
              <span className="font-semibold">{comment.user}</span>
            </div>
            <p>{comment.content}</p>
            <div className="mt-2">
              <Input
                type="text"
                placeholder="Add a reply"
                className="w-full"
                onKeyPress={(e) => {
                  if (e.key === 'Enter') {
                    handleAddReply(comment.id, e.currentTarget.value);
                    e.currentTarget.value = '';
                  }
                }}
              />
            </div>
            {comment.replies.length > 0 && (
              <div className="mt-4 pl-4 border-l-2 border-gray-300">
                {comment.replies.map(reply => (
                  <Card key={reply.id} className="p-4 mb-2">
                    <div className="flex justify-between items-center mb-2">
                      <span className="font-semibold">{reply.user}</span>
                    </div>
                    <p>{reply.content}</p>
                  </Card>
                ))}
              </div>
            )}
          </Card>
        ))}
      </div>
    </div>
  );
};

export default DiscussionForum;