// Generated by FrontendAgent
import React from 'react';
import { Button, Input, Card } from '@/components/ui';
import { cn } from '@/lib/utils';

interface FooterProps {
  className?: string;
}

const Footer: React.FC<FooterProps> = ({ className }) => {
  return (
    <footer className={cn('bg-gray-800 text-white py-8', className)}>
      <div className="container mx-auto px-4">
        <div className="flex flex-col md:flex-row justify-between items-center mb-8">
          <div className="mb-4 md:mb-0">
            <h2 className="text-2xl font-bold">Contact Us</h2>
            <p className="mt-2">Have questions or need support? Reach out to us!</p>
          </div>
          <div className="flex space-x-4">
            <Button variant="outline" className="bg-white text-gray-800 hover:bg-gray-100">
              Email Us
            </Button>
            <Button variant="outline" className="bg-white text-gray-800 hover:bg-gray-100">
              Call Us
            </Button>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card className="bg-gray-900 p-6">
            <h3 className="text-xl font-semibold mb-4">Address</h3>
            <p>123 Learning Lane</p>
            <p>Education City, EDU 12345</p>
          </Card>
          <Card className="bg-gray-900 p-6">
            <h3 className="text-xl font-semibold mb-4">Email</h3>
            <p>support@learnify.com</p>
            <p>info@learnify.com</p>
          </Card>
          <Card className="bg-gray-900 p-6">
            <h3 className="text-xl font-semibold mb-4">Phone</h3>
            <p>(123) 456-7890</p>
            <p>(123) 987-6543</p>
          </Card>
        </div>
        <div className="mt-8">
          <h3 className="text-xl font-semibold mb-4">Subscribe to Our Newsletter</h3>
          <div className="flex flex-col md:flex-row space-y-4 md:space-y-0 md:space-x-4">
            <Input
              type="email"
              placeholder="Enter your email"
              className="flex-grow"
            />
            <Button className="bg-blue-500 hover:bg-blue-600">
              Subscribe
            </Button>
          </div>
        </div>
        <div className="mt-8 text-center">
          <p>&copy; {new Date().getFullYear()} Learnify. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;