// Generated by FrontendAgent
import React from 'react';
import { Button, Input } from '@/components/ui';
import { cn } from '@/lib/utils';

interface HeaderProps {
  isAuthenticated: boolean;
  onLogout: () => void;
  onSearch: (query: string) => void;
}

const Header: React.FC<HeaderProps> = ({ isAuthenticated, onLogout, onSearch }) => {
  const [searchQuery, setSearchQuery] = React.useState('');

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    onSearch(searchQuery);
  };

  return (
    <header className="bg-gray-800 text-white shadow-md">
      <div className="container mx-auto px-4 py-4 flex justify-between items-center">
        <div className="text-xl font-bold">CourseHub</div>
        <nav className="hidden md:flex space-x-4">
          <a href="/courses" className="hover:text-gray-300">Courses</a>
          <a href="/assignments" className="hover:text-gray-300">Assignments</a>
          <a href="/forum" className="hover:text-gray-300">Forum</a>
          {isAuthenticated && <a href="/profile" className="hover:text-gray-300">Profile</a>}
        </nav>
        <div className="flex items-center space-x-4">
          <form onSubmit={handleSearch} className="flex items-center">
            <Input
              type="text"
              placeholder="Search courses..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="px-3 py-2 rounded-l-md"
            />
            <Button type="submit" className="px-3 py-2 rounded-r-md bg-blue-500 text-white">
              Search
            </Button>
          </form>
          {isAuthenticated ? (
            <Button onClick={onLogout} className="bg-red-500 text-white px-4 py-2 rounded-md">
              Logout
            </Button>
          ) : (
            <div className="space-x-2">
              <a href="/login" className="text-blue-300 hover:text-blue-400">Login</a>
              <a href="/register" className="text-blue-300 hover:text-blue-400">Register</a>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};

export default Header;