// Generated by FrontendAgent
import React, { useState } from 'react';
import { Button, Input, Card } from '@/components/ui';
import { cn } from '@/lib/utils';

interface LoginModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLogin: (email: string, password: string) => void;
}

const LoginModal: React.FC<LoginModalProps> = ({ isOpen, onClose, onLogin }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onLogin(email, password);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <Card className="w-full max-w-md p-6">
        <h2 className="text-2xl font-bold mb-6 text-center">Login</h2>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <Input
              type="email"
              placeholder="Email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className={cn('w-full p-2 border rounded', {
                'border-red-500': !email,
              })}
            />
          </div>
          <div className="mb-4">
            <Input
              type="password"
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className={cn('w-full p-2 border rounded', {
                'border-red-500': !password,
              })}
            />
          </div>
          <div className="flex justify-between items-center">
            <Button type="submit" className="w-full bg-blue-500 text-white py-2 rounded">
              Login
            </Button>
          </div>
        </form>
        <div className="mt-4 text-center">
          <Button onClick={onClose} className="text-blue-500">
            Cancel
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default LoginModal;